apiVersion: v1
kind: Service
metadata:
  name: quipd
  namespace: quip-system
spec:
  selector:
    app.kubernetes.io/name: quip
  ports:
    - name: quic
      port: 4433
      protocol: UDP
      targetPort: 4433
