apiVersion: v1
kind: Service
metadata:
  name: quicnetd
  namespace: quicnet-system
spec:
  selector:
    app.kubernetes.io/name: quicnet
  ports:
    - name: quic-udp
      protocol: UDP
      port: 4433
      targetPort: 4433

